In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### Loading dataset

In [31]:
df = pd.read_csv('../Dataset/Raw/finance_transactions.csv')

In [32]:
df.shape

(50069, 15)

In [33]:
df.head()

,transaction_id,transaction_date,account_id,customer_id,transaction_type,channel,merchant_category,amount,fee_amount,tax_amount,currency,transaction_status,is_fraud,risk_score,reference_no
0,T00000001,21-02-2025,A001795,C00629,Investment,Mobile App,Food Delivery,24721.24,123.61,22.25,INR,Success,No,63,REF8835851139
1,T00000002,28-01-2023,A004859,C02038,Transfer,UPI,Groceries,18711.77,93.56,16.84,INR,Success,No,21,REF9409811139
2,T00000003,25-06-2024,A003081,C00652,Transfer,Net Banking,Groceries,45865.90,0.00,0.00,INR,Success,No,25,REF1704628312
3,T00000004,20-02-2025,A004122,C01357,Withdrawal,Auto Debit,Salary,4310.91,NaN,0.78,INR,Failed,No,43,REF3937614748
4,T00000005,06-08-2024,A004150,C02547,Deposit,Branch,Shopping,11646.45,0.00,0.00,INR,Success,No,5,REF5855288886

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50069 entries, 0 to 50068
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      50069 non-null  str
 1   transaction_date    50069 non-null  str
 2   account_id          50069 non-null  str
 3   customer_id         50069 non-null  str
 4   transaction_type    50069 non-null  str
 5   channel             50069 non-null  str
 6   merchant_category   50069 non-null  str
 7   amount              50069 non-null  float64
 8   fee_amount          50045 non-null  float64
 9   tax_amount          50069 non-null  float64
 10  currency            50069 non-null  str
 11  transaction_status  50069 non-null  str
 12  is_fraud            50069 non-null  str
 13  risk_score          50069 non-null  int64
 14  reference_no        50069 non-null  str
dtypes: float64(3), int64(1), str(11)
memory usage: 5.7 MB

In [35]:
cols = ["transaction_type", "channel", "merchant_category", "currency", "transaction_status", "is_fraud"]
for cols in cols:
    print(f"{cols} : {df[cols].unique()}")
    print("--")

transaction_type : <StringArray>
[     'Investment',        'Transfer',      'Withdrawal',         'Deposit',
        'Loan EMI', 'Interest Credit',    'Card Payment',    'Bill Payment',
      'Fee Charge',          'Refund']
Length: 10, dtype: str
--
channel : <StringArray>
[            'Mobile App',                    'UPI',         '   Net Banking',
             'Auto Debit',                 'Branch',           '  Mobile App',
                    'ATM', '            Mobile App',                  '  POS',
                    'POS',                  'ATM  ',            'Net Banking',
             'M@bile App']
Length: 13, dtype: str
--
merchant_category : <StringArray>
['Food Delivery',     'Groceries',        'Salary',      'Shopping',
     'Insurance',     'Education',          'Rent',    'Healthcare',
  'Bank Charges',          'Fuel',        'Travel',     'Utilities',
 'Entertainment',   'Mutual Fund']
Length: 14, dtype: str
--
currency : <StringArray>
['INR', 'inr', 'inR']
Length: 3, dtype: str
--
transaction_status : <StringArray>
['Success', 'Failed', 'Pending']
Length: 3, dtype: str
--
is_fraud : <StringArray>
['No', 'Yes']
Length: 2, dtype: str
--

## Cleaning data and changing data types

In [36]:
df['transaction_type'] =df['transaction_type'].astype('category')

In [37]:
df['channel'].unique()

<StringArray>
[            'Mobile App',                    'UPI',         '   Net Banking',
             'Auto Debit',                 'Branch',           '  Mobile App',
                    'ATM', '            Mobile App',                  '  POS',
                    'POS',                  'ATM  ',            'Net Banking',
             'M@bile App']
Length: 13, dtype: str

In [38]:
df['channel'] =df['channel'].str.strip()

In [39]:
df['channel'] = df['channel'].replace({"M@bile App": "Mobile App"})

In [40]:
df['channel'].unique()

<StringArray>
['Mobile App', 'UPI', 'Net Banking', 'Auto Debit', 'Branch', 'ATM', 'POS']
Length: 7, dtype: str

In [41]:
df['channel'] =df['channel'].astype('category')

In [42]:
df['merchant_category'] = df['merchant_category'].astype('category')

In [43]:
df['currency'].unique()

<StringArray>
['INR', 'inr', 'inR']
Length: 3, dtype: str

In [44]:
df['currency'] = df['currency'].replace({"inr":"INR","inR":"INR"})

In [45]:
df['currency'].unique()

<StringArray>
['INR']
Length: 1, dtype: str

In [46]:
df['currency'] =df['currency'].astype('category')

In [47]:
df['is_fraud'] =df['is_fraud'].astype('category')

In [48]:
df['transaction_status'] = df['transaction_status'].astype('category')

In [49]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'], format='%d-%m-%Y')

In [50]:
## checking for missing values
df.isnull().sum()

transaction_id         0
transaction_date       0
account_id             0
customer_id            0
transaction_type       0
channel                0
merchant_category      0
amount                 0
fee_amount            24
tax_amount             0
currency               0
transaction_status     0
is_fraud               0
risk_score             0
reference_no           0
dtype: int64

In [51]:
df = df.dropna(subset=['fee_amount'])

In [52]:
df.shape

(50045, 15)

## Checking duplicate values

In [53]:
df.duplicated().sum()

np.int64(68)

In [54]:
## dropping duplicate values
df = df.drop_duplicates()

In [55]:
df = df.reset_index(drop=True)

In [56]:
df.shape

(49977, 15)

## Adding Year and month columns

In [58]:
df['transaction_year'] = df['transaction_date'].dt.year

In [68]:
df['transaction_month'] = df['transaction_date'].dt.month

In [69]:
df.shape

(49977, 17)

In [62]:
df.head()

,transaction_id,transaction_date,account_id,customer_id,transaction_type,channel,merchant_category,amount,fee_amount,tax_amount,currency,transaction_status,is_fraud,risk_score,reference_no,transaction_year,transaction_month
0,T00000001,2025-02-21,A001795,C00629,Investment,Mobile App,Food Delivery,24721.24,123.61,22.25,INR,Success,No,63,REF8835851139,2025,2
1,T00000002,2023-01-28,A004859,C02038,Transfer,UPI,Groceries,18711.77,93.56,16.84,INR,Success,No,21,REF9409811139,2023,1
2,T00000003,2024-06-25,A003081,C00652,Transfer,Net Banking,Groceries,45865.90,0.00,0.00,INR,Success,No,25,REF1704628312,2024,6
3,T00000005,2024-08-06,A004150,C02547,Deposit,Branch,Shopping,11646.45,0.00,0.00,INR,Success,No,5,REF5855288886,2024,8
4,T00000006,2024-10-01,A007909,C04090,Withdrawal,Branch,Groceries,3972.11,0.00,0.00,INR,Pending,No,4,REF2066285792,2024,10

## Saving the final file

In [67]:
df.to_csv("../Dataset/Cleaned/Cleaned_finance_transactions.csv")